-- ============================================================
-- Tabella: relazioni_tecniche
-- Relazioni di lavorazione e dichiarazioni tecniche collegate ai clienti
-- ============================================================

CREATE TABLE IF NOT EXISTS relazioni_tecniche (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    cliente_id          UUID REFERENCES clients(id) ON DELETE SET NULL,
    tipo_documento      TEXT NOT NULL DEFAULT 'relazione_lavorazione'
                        CHECK (tipo_documento IN ('relazione_lavorazione', 'dichiarazione_tecnica')),
    data_intervento     DATE NOT NULL DEFAULT CURRENT_DATE,
    luogo_intervento    TEXT,
    oggetto             TEXT NOT NULL,
    descrizione         TEXT,
    intervento_eseguito TEXT,
    esito               TEXT,
    note                TEXT,
    tecnico             TEXT,
    cliente_nome        TEXT NOT NULL,
    cliente_indirizzo   TEXT,
    cliente_citta       TEXT,
    cliente_cap         TEXT,
    cliente_provincia   TEXT,
    cliente_telefono    TEXT,
    cliente_email       TEXT,
    cliente_partita_iva TEXT,
    cliente_codice_fiscale TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_relazioni_tecniche_cliente_id
    ON relazioni_tecniche(cliente_id);
CREATE INDEX IF NOT EXISTS idx_relazioni_tecniche_data_intervento
    ON relazioni_tecniche(data_intervento DESC);

CREATE OR REPLACE FUNCTION update_relazioni_tecniche_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_relazioni_tecniche_updated_at ON relazioni_tecniche;
CREATE TRIGGER trg_relazioni_tecniche_updated_at
    BEFORE UPDATE ON relazioni_tecniche
    FOR EACH ROW EXECUTE FUNCTION update_relazioni_tecniche_updated_at();

ALTER TABLE relazioni_tecniche ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "relazioni_tecniche_all" ON relazioni_tecniche;
CREATE POLICY "relazioni_tecniche_all" ON relazioni_tecniche
    FOR ALL USING (true) WITH CHECK (true);
